channels = [
'Интер',
'Amedia Hit',
'Amedia Hit HD',
'Amedia Premium',
'Amedia Premium HD',
'Ani',
'Animal Planet',
'Animal Planet HD',
'Eurosport 1',
'Fox',
'Fox HD',
'Fox Life',
'Fox Life HD',
'History Channel',
'History Channel HD',
'National Geographic HD',
'Матч ТВ',
'Матч ТВ HD',
'Матч! Футбол 1',
'Матч! Футбол 1 HD',
'Матч! Футбол 1 HD Резерв 1',
'Матч! Футбол 1 HD Резерв 2',
'Матч! Футбол 1 HD Резерв 3',
'Матч! Футбол 1 Резерв 1',
'Матч! Футбол 1 Резерв 2',
'Матч! Футбол 1 Резерв 3',
'Матч! Футбол 2',
'Матч! Футбол 2 HD',
'Матч! Футбол 3',
'Матч! Футбол 3 HD',
'Футбoл HD',
'Футбол',
'Футбол 1 HD',
'Футбол 2 (Украина)',
'Футбол 2 HD',
]



